# Generated by data-raw/SITES.R. DO NOT EDIT!!
#' sersapi::sites A sf points data frame with information about electrofishing sites in SERS
#'
#' Data from the Swedish Electrofishing Register (SERS) containing information about electrofishing sites.
#' The geographical coordinates are in the WGS84 coordinate reference system.
#' The documentation is based on the Excel file provided by SLU and avaliable in Swedish only.
#'
#' @format A data frame with 23 variables:
#' \describe{
#'   \item{LAN}{Länen kodas 1 till 25 (Stockholms till Norrbottens län).}
#'   \item{HFLODOMR}{Huvudflodområdesnummer enligt SMHI:s numrering (Vattendragsregistret).}
#'   \item{BIFLNR}{Biflödesnummer enligt SMHI (Vattendragsregistret).}
#'   \item{VDRAGNAM}{Vattendragets namn.}
#'   \item{XKOORVDR}{Vattendragets mynningskoordinat i X-led (nord-syd) enligt SMHI (Vattendragsregistret).}
#'   \item{YKOORVDR}{Vattendragets mynningskoordinat i Y-led (väst-öst) enligt SMHI (Vattendragsregistret).}
#'   \item{LOKALNAM}{Elfiskelokalens namn}
#'   \item{LOKALNR}{Elfiskelokalens nummer (om blankt saknas lokalnummer för aktuell elfiskelokal).}
#'   \item{XKOORLOK}{X-koordinat (nord-syd; sexsiffrig RT90, 2.5 gon väst) för elfiskelokalens nedersta punkt.}
#'   \item{YKOORLOK}{Y-koordinat (väst-öst; sexsiffrig RT90, 2.5 gon väst) för elfiskelokalens nedersta punkt.}
#'   \item{HOH}{Höjd över havet i meter.}
#'   \item{AVRIOMRK}{Avrinningsområdets storlek uppströms elfiskelokalen (km2). Anges enbart i fyra klasser  (<10, <100, <1000 resp >1000).}
#'   \item{ANDSJOPR}{Andelen sjöar i % av avrinningsområdet uppströms elfiskelokalen. Anges enbart i fyra klasser (<1, <5, <10, >10).}
#'   \item{AVSTUPP}{Avstånd (km) till uppströms sjö eller större sel (lugnparti) om minst 1 hektar i huvudfåran.}
#'   \item{AVSTNER}{Avstånd (km) till nedströms sjö eller större sel (lugnparti) om minst 1 hektar i huvudfåran.}
#'   \item{KOMMUNNR}{Anger vilken kommun som elfiskelokalen ligger i enligt SCB.}
#'   \item{KOMMUN}{Namn på kommunen där elfiskelokalen är lokaliserad.}
#'   \item{TOPOKART}{Här anges vilken topografisk karta elfiskelokalen ligger på, ex 10B SO. Lämnas tomt om ej angivet.}
#'   \item{X_RT90_SJU}{X-koordinat (nord-syd; sjusiffrig RT90, 2.5 gon väst) för elfiskelokalens nedersta punkt.}
#'   \item{Y_RT90_SJU}{Y-koordinat (väst-öst; sjusiffrig RT90, 2.5 gon väst) för elfiskelokalens nedersta punkt.}
#'   \item{S99TM_N}{Koordinat (nord-syd, Sweref99 TM) för elfiskelokalens nedersta punkt. Obs. ska ej anges på elfiskeprotokoll!}
#'   \item{S99TM_E}{Koordinat (väst-öst, Sweref99 TM) för elfiskelokalens nedersta punkt. Obs. ska ej anges på elfiskeprotokoll!}
#'   \item{DDLAT}{Latitud för elfiskelokalen (WGS84) för elfiskelokalens nedersta punkt. Obs. ska ej anges på elfiskeprotokoll!}
#'   \item{DDLONG}{Latitud för elfiskelokalen (WGS84) för elfiskelokalens nedersta punkt. Obs. ska ej anges på elfiskeprotokoll!}
#' }
#' @source
#'    Swedish Electrofishing Register (SERS)
#'    \url{https://www.slu.se/en/departments/aquatic-resources1/databases/database-for-testfishing-in-streams/}
"sites"